const StigData = [
  {
    number: "1",
    percent: 100,
    stig1: "/prometheus-gg/img/stigs/sushang/sushang-t.webp",
    stig2: "/prometheus-gg/img/stigs/sushang/sushang-m.webp",
    stig3: "/prometheus-gg/img/stigs/sushang/sushang-b.webp",
    name1: "Li Sushang: Shenzou Reminiscence",
    name2: "Li Sushang: Shenzou Reminiscence",
    name3: "Li Sushang: Shenzou Reminiscence",
  },
  {
    number: "2",
    percent: 97.02,
    stig1: "/prometheus-gg/img/stigs/sushang/sushang-t.webp",
    stig2: "/prometheus-gg/img/stigs/beach/beach-m.webp",
    stig3: "/prometheus-gg/img/stigs/sushang/sushang-b.webp",
    name1: "Li Sushang: Shenzou Reminiscence",
    name2: "Mei - Beach Party",
    name3: "Li Sushang: Shenzou Reminiscence",
  },
  {
    number: "3",
    percent: 92.71,
    stig1: "/prometheus-gg/img/stigs/kiana/kiana-t.webp",
    stig2: "/prometheus-gg/img/stigs/thales/thales-m.webp",
    stig3: "/prometheus-gg/img/stigs/kiana/kiana-b.webp",
    name1: "Kiana Kaslana",
    name2: "Thales",
    name3: "Kiana Kaslana",
  },
  {
    number: "4",
    percent: 89.6,
    stig1: "/prometheus-gg/img/stigs/himeko/himeko-t.webp",
    stig2: "/prometheus-gg/img/stigs/kiana/kiana-m.webp",
    stig3: "/prometheus-gg/img/stigs/kiana/kiana-b.webp",
    name1: "Murata Himeko",
    name2: "Kiana Kaslana",
    name3: "Kiana Kaslana",
  },
  {
    number: "5",
    percent: 87.44,
    stig1: "/prometheus-gg/img/stigs/turg/turg-t.webp",
    stig2: "/prometheus-gg/img/stigs/thales/thales-m.webp",
    stig3: "/prometheus-gg/img/stigs/turg/turg-b.webp",
    name1: "Turgenev",
    name2: "Thales",
    name3: "Turgenev",
  },
];

export default StigData;
