const ValkData = [
  {
    valkname: "Herrscher of Finality",
    character: "kiana",
    elysian: true,
    augment: false,
    suit: "img",
    element: "fire",
    rank: "S",
    src: "/img/valks/kiana/HOFIicon.webp",
  },
  {
    valkname: "Herrscher of Flamescion",
    character: "kiana",
    elysian: true,
    augment: false,
    suit: "psy",
    element: "fire",
    rank: "S",
    src: "/img/valks/kiana/HOFSicon.webp",
  },
  {
    valkname: "Herrscher of the Void",
    character: "kiana",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "S",
    src: "/img/valks/kiana/HOVicon.webp",
  },
  {
    valkname: "Knight Moonbeam",
    character: "kiana",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "S",
    src: "/img/valks/kiana/KMBicon.webp",
  },
  {
    valkname: "Valkyrie Ranger",
    character: "kiana",
    elysian: false,
    augment: true,
    suit: "mech",
    element: "physical",
    rank: "A",
    src: "/img/valks/kiana/VRicon.webp",
  },
  {
    valkname: "Divine Prayer",
    character: "kiana",
    elysian: true,
    augment: false,
    suit: "psy",
    element: "physical",
    rank: "A",
    src: "/img/valks/kiana/DPicon.webp",
  },
  {
    valkname: "White Comet",
    character: "kiana",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "physical",
    rank: "B",
    src: "/img/valks/kiana/WCicon.webp",
  },
  {
    valkname: "Herrscher of Origin",
    character: "mei",
    elysian: true,
    augment: false,
    suit: "img",
    element: "lightning",
    rank: "S",
    src: "/img/valks/mei/HOOicon.webp",
  },
  {
    valkname: "Herrscher of Thunder",
    character: "mei",
    elysian: true,
    augment: false,
    suit: "psy",
    element: "lightning",
    rank: "S",
    src: "/img/valks/mei/HOTicon.webp",
  },
  {
    valkname: "Lightning Empress",
    character: "mei",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "lightning",
    rank: "S",
    src: "/img/valks/mei/LEicon.webp",
  },
  {
    valkname: "Shadow Dash",
    character: "mei",
    elysian: false,
    augment: true,
    suit: "mech",
    element: "physical",
    rank: "A",
    src: "/img/valks/mei/SDicon.webp",
  },
  {
    valkname: "Valkyrie Bladestrike",
    character: "mei",
    elysian: true,
    augment: true,
    suit: "bio",
    element: "physical",
    rank: "A",
    src: "/img/valks/mei/VBicon.webp",
  },
  {
    valkname: "Crimson Impulse",
    character: "mei",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "B",
    src: "/img/valks/mei/CIicon.webp",
  },
  {
    valkname: "Herrscher of Truth",
    character: "bronya",
    elysian: true,
    augment: false,
    suit: "img",
    element: "ice",
    rank: "S",
    src: "/img/valks/bronya/HOTRicon.webp",
  },
  {
    valkname: "Silverwing N-EX",
    character: "bronya",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "ice",
    rank: "S",
    src: "/img/valks/bronya/SNEXicon.webp",
  },
  {
    valkname: "Herrscher of Reason",
    character: "bronya",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "ice",
    rank: "S",
    src: "/img/valks/bronya/HORicon.webp",
  },
  {
    valkname: "Haxx0r Bunny",
    character: "bronya",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "ice",
    rank: "A",
    src: "/img/valks/bronya/HBicon.webp",
  },
  {
    valkname: "Black Nucleus",
    character: "bronya",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "S",
    src: "/img/valks/bronya/BNicon.webp",
  },
  {
    valkname: "Dimension Breaker",
    character: "bronya",
    elysian: false,
    augment: false,
    suit: "mech",
    element: "physical",
    rank: "S",
    src: "/img/valks/bronya/DBicon.webp",
  },
  {
    valkname: "Wolf's Dawn",
    character: "bronya",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "physical",
    rank: "A",
    src: "/img/valks/bronya/WDicon.webp",
  },
  {
    valkname: "Snowy Sniper",
    character: "bronya",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "A",
    src: "/img/valks/bronya/SSicon.webp",
  },
  {
    valkname: "Yamabuki Armor",
    character: "bronya",
    elysian: false,
    augment: true,
    suit: "psy",
    element: "physical",
    rank: "A",
    src: "/img/valks/bronya/YAicon.webp",
  },
  {
    valkname: "Valkyrie Chariot",
    character: "bronya",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "physical",
    rank: "B",
    src: "/img/valks/bronya/VCicon.webp",
  },
  {
    valkname: "Herrscher of Sentience",
    character: "fuhua",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "S",
    src: "/img/valks/fuhua/HOSicon.webp",
  },
  {
    valkname: "Azure Empyrea",
    character: "fuhua",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "fire",
    rank: "S",
    src: "/img/valks/fuhua/AEicon.webp",
  },
  {
    valkname: "Shadow Knight",
    character: "fuhua",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "lightning",
    rank: "S",
    src: "/img/valks/fuhua/SKicon.webp",
  },
  {
    valkname: "Phoenix",
    character: "fuhua",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "fire",
    rank: "S",
    src: "/img/valks/fuhua/PXicon.webp",
  },
  {
    valkname: "Night Squire",
    character: "fuhua",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "A",
    src: "/img/valks/fuhua/NSicon.webp",
  },
  {
    valkname: "Valkyrie Accipiter",
    character: "fuhua",
    elysian: false,
    augment: true,
    suit: "psy",
    element: "lightning",
    rank: "A",
    src: "/img/valks/fuhua/VAicon.webp",
  },
  {
    valkname: "Violet Executer",
    character: "theresa",
    elysian: true,
    augment: true,
    suit: "mech",
    element: "physical",
    rank: "S",
    src: "/img/valks/theresa/VEicon.webp",
  },
  {
    valkname: "Celestial Hymn",
    character: "theresa",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "S",
    src: "/img/valks/theresa/CHicon.webp",
  },
  {
    valkname: "Starlit Astrologos",
    character: "theresa",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "A",
    src: "/img/valks/theresa/SAicon.webp",
  },
  {
    valkname: "Luna Kindred",
    character: "theresa",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "A",
    src: "/img/valks/theresa/LKicon.webp",
  },
  {
    valkname: "Sakuno Rondo",
    character: "theresa",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "fire",
    rank: "A",
    src: "/img/valks/theresa/SRicon.webp",
  },
  {
    valkname: "Valkyrie Pledge",
    character: "theresa",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "lightning",
    rank: "A",
    src: "/img/valks/theresa/VPicon.webp",
  },
  {
    valkname: "Vermilion Knight: Eclipse",
    character: "himeko",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "fire",
    rank: "S",
    src: "/img/valks/himeko/VKEicon.webp",
  },
  {
    valkname: "Blood Rose",
    character: "himeko",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "fire",
    rank: "S",
    src: "/img/valks/himeko/BRicon.webp",
  },
  {
    valkname: "Scarlet Fusion",
    character: "himeko",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "lightning",
    rank: "A",
    src: "/img/valks/himeko/SFicon.webp",
  },
  {
    valkname: "Kriegsmesser",
    character: "himeko",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "ice",
    rank: "A",
    src: "/img/valks/himeko/KRicon.webp",
  },
  {
    valkname: "Valkyrie Triumph",
    character: "himeko",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "A",
    src: "/img/valks/himeko/VTicon.webp",
  },
  {
    valkname: "Battle Storm",
    character: "himeko",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "B",
    src: "/img/valks/himeko/BSicon.webp",
  },
  {
    valkname: "Starchasm Nyx",
    character: "seele",
    elysian: true,
    augment: false,
    suit: "qua",
    element: "ice",
    rank: "S",
    src: "/img/valks/seele/SNyxIcon.webp",
  },
  {
    valkname: "Stygian Nymph",
    character: "seele",
    elysian: false,
    augment: false,
    suit: "qua",
    element: "physical",
    rank: "S",
    src: "/img/valks/seele/SNicon.webp",
  },
  {
    valkname: "Swallowtail Phantasm",
    character: "seele",
    elysian: false,
    augment: false,
    suit: "qua",
    element: "physical",
    rank: "A",
    src: "/img/valks/seele/SPicon.webp",
  },
  {
    valkname: "Palatinus Equinox",
    character: "durandal",
    elysian: true,
    augment: false,
    suit: "img",
    element: "physical",
    rank: "S",
    src: "/img/valks/durandal/PEicon.webp",
  },
  {
    valkname: "Dea Anchora",
    character: "durandal",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "fire",
    rank: "S",
    src: "/img/valks/durandal/DAicon.webp",
  },
  {
    valkname: "Bright Knight: Excelsis",
    character: "durandal",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "physical",
    rank: "S",
    src: "/img/valks/durandal/BKEicon.webp",
  },
  {
    valkname: "Valkyrie Gloria",
    character: "durandal",
    elysian: true,
    augment: false,
    suit: "qua",
    element: "fire",
    rank: "A",
    src: "/img/valks/durandal/VGicon.webp",
  },
  {
    valkname: "Spina Astera",
    character: "rita",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "fire",
    rank: "S",
    src: "/img/valks/rita/SPAicon.webp",
  },
  {
    valkname: "Fallen Rosemary",
    character: "rita",
    elysian: true,
    augment: false,
    suit: "qua",
    element: "lightning",
    rank: "S",
    src: "/img/valks/rita/FRicon.webp",
  },
  {
    valkname: "Argent Knight: Artemis",
    character: "rita",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "ice",
    rank: "S",
    src: "/img/valks/rita/AKAicon.webp",
  },
  {
    valkname: "Phantom Iron",
    character: "rita",
    elysian: false,
    augment: false,
    suit: "mech",
    element: "lightning",
    rank: "A",
    src: "/img/valks/rita/PIicon.webp",
  },
  {
    valkname: "Umbral Rose",
    character: "rita",
    elysian: false,
    augment: false,
    suit: "psy",
    element: "physical",
    rank: "A",
    src: "/img/valks/rita/URicon.webp",
  },
  {
    valkname: "Goushinnso Memento",
    character: "sakura",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "ice",
    rank: "S",
    src: "/img/valks/sakura/GMicon.webp",
  },
  {
    valkname: "Darkbolt Jonin",
    character: "sakura",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "lightning",
    rank: "A",
    src: "/img/valks/sakura/DJicon.webp",
  },
  {
    valkname: "Flame Sakitama",
    character: "sakura",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "fire",
    rank: "A",
    src: "/img/valks/sakura/FSicon.webp",
  },
  {
    valkname: "Gyakushinn Miko",
    character: "sakura",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "A",
    src: "/img/valks/sakura/MikoIcon.webp",
  },
  {
    valkname: "Sixth Serenade",
    character: "kallen",
    elysian: true,
    augment: false,
    suit: "psy",
    element: "ice",
    rank: "S",
    src: "/img/valks/kallen/6Sicon.webp",
  },
  {
    valkname: "Sundenjager",
    character: "kallen",
    elysian: false,
    augment: false,
    suit: "mech",
    element: "physical",
    rank: "A",
    src: "/img/valks/kallen/SJicon.webp",
  },
  {
    valkname: "Ritual Imayoh",
    character: "kallen",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "physical",
    rank: "A",
    src: "/img/valks/kallen/RIicon.webp",
  },
  {
    valkname: "Molotov Cherry",
    character: "rozaliya",
    elysian: true,
    augment: true,
    suit: "psy",
    element: "physical",
    rank: "S",
    src: "/img/valks/olenyeva/MCicon.webp",
  },
  {
    valkname: "Blueberry Blitz",
    character: "liliya",
    elysian: false,
    augment: false,
    suit: "mech",
    element: "physical",
    rank: "A",
    src: "/img/valks/olenyeva/BBicon.webp",
  },
  {
    valkname: "Blazing Hope",
    character: "asuka",
    elysian: false,
    augment: false,
    suit: "bio",
    element: "physical",
    rank: "A",
    src: "/img/valks/misc/BHicon.webp",
  },
  {
    valkname: "Prinzessin der Verurteilung!",
    character: "fischl",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "lightning",
    rank: "A",
    src: "/img/valks/misc/PVicon.webp",
  },
  {
    valkname: "Miss Pink Elf",
    character: "elysia",
    elysian: true,
    augment: false,
    suit: "psy",
    element: "physical",
    rank: "S",
    src: "/img/valks/flamechaser/MPEicon.webp",
  },
  {
    valkname: "Herrscher of Human: Ego",
    character: "elysia",
    elysian: true,
    augment: false,
    suit: "psy",
    element: "ice",
    rank: "S",
    src: "/img/valks/flamechaser/HOHEicon.webp",
  },
  {
    valkname: "Disciplinary Perdition",
    character: "aponia",
    elysian: true,
    augment: false,
    suit: "bio",
    element: "lightning",
    rank: "S",
    src: "/img/valks/flamechaser/DPEicon.webp",
  },
  {
    valkname: "Golden Diva",
    character: "eden",
    elysian: true,
    augment: false,
    suit: "img",
    element: "lightning",
    rank: "A",
    src: "/img/valks/flamechaser/GDicon.webp",
  },
  {
    valkname: "Reverist Calico",
    character: "pardo",
    elysian: true,
    augment: false,
    suit: "img",
    element: "ice",
    rank: "A",
    src: "/img/valks/flamechaser/RCicon.webp",
  },
  {
    valkname: "Infinite Ouroboros",
    character: "mobius",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "lightning",
    rank: "S",
    src: "/img/valks/flamechaser/IOicon.webp",
  },
  {
    valkname: "Helical Contraption",
    character: "vill-v",
    elysian: true,
    augment: false,
    suit: "qua",
    element: "fire",
    rank: "S",
    src: "/img/valks/flamechaser/HCicon.webp",
  },
  {
    valkname: "Starry Impression",
    character: "griseo",
    elysian: true,
    augment: false,
    suit: "psy",
    element: "physical",
    rank: "A",
    src: "/img/valks/flamechaser/SIicon.webp",
  },
  {
    valkname: "Jade Knight",
    character: "sushang",
    elysian: true,
    augment: false,
    suit: "psy",
    element: "ice",
    rank: "S",
    src: "/img/valks/immoblades/JKicon.webp",
  },
  {
    valkname: "Valkyrie Quicksand",
    character: "susannah",
    elysian: true,
    augment: false,
    suit: "qua",
    element: "physical",
    rank: "A",
    src: "/img/valks/immoblades/VQicon.webp",
  },
  {
    valkname: "Midnight Absinthe",
    character: "raven",
    elysian: true,
    augment: false,
    suit: "img",
    element: "fire",
    rank: "A",
    src: "/img/valks/serpent/MAicon.webp",
  },
  {
    valkname: "Dreamweaver",
    character: "misteln",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "physical",
    rank: "S",
    src: "/img/valks/serpent/DWicon.webp",
  },
  {
    valkname: "Terminal Aide 0017",
    character: "prometheus",
    elysian: true,
    augment: false,
    suit: "img",
    element: "physical",
    rank: "A",
    src: "/img/valks/serpent/TAicon.webp",
  },
  {
    valkname: "Chrono Navi",
    character: "ai",
    elysian: true,
    augment: false,
    suit: "mech",
    element: "fire",
    rank: "A",
    src: "/img/valks/misc/CNicon.webp",
  },
];

export default ValkData;
