const StigData = [
  {
    number: "1",
    percent: 100,
    stig1: "/prometheus-gg/img/stigs/kiana/kiana-t.webp",
    stig2: "/prometheus-gg/img/stigs/kiana/kiana-m.webp",
    stig3: "/prometheus-gg/img/stigs/kiana/kiana-b.webp",
    name1: "Kiana Kaslana",
    name2: "Kiana Kaslana",
    name3: "Kiana Kaslana",
  },
  {
    number: "2",
    percent: 90.78,
    stig1: "/prometheus-gg/img/stigs/kiana/kiana-t.webp",
    stig2: "/prometheus-gg/img/stigs/kiana/kiana-m.webp",
    stig3: "/prometheus-gg/img/stigs/newton/newton-b.webp",
    name1: "Kiana Kaslana",
    name2: "Kiana Kaslana",
    name3: "Newton",
  },
  {
    number: "3",
    percent: 90.65,
    stig1: "/prometheus-gg/img/stigs/kiana/kiana-t.webp",
    stig2: "/prometheus-gg/img/stigs/thales/thales-m.webp",
    stig3: "/prometheus-gg/img/stigs/kiana/kiana-b.webp",
    name1: "Kiana Kaslana",
    name2: "Thales",
    name3: "Kiana Kaslana",
  },
  {
    number: "4",
    percent: 86.26,
    stig1: "/prometheus-gg/img/stigs/himeko/himeko-t.webp",
    stig2: "/prometheus-gg/img/stigs/kiana/kiana-m.webp",
    stig3: "/prometheus-gg/img/stigs/kiana/kiana-b.webp",
    name1: "Murata Himeko",
    name2: "Kiana Kaslana",
    name3: "Kiana Kaslana",
  },
  {
    number: "5",
    percent: 84.65,
    stig1: "/prometheus-gg/img/stigs/himeko/himeko-t.webp",
    stig2: "/prometheus-gg/img/stigs/thales/thales-m.webp",
    stig3: "/prometheus-gg/img/stigs/newton/newton-b.webp",
    name1: "Murata Himeko",
    name2: "Thales",
    name3: "Newton",
  },
];

export default StigData;
